version: '3'

services:

  # MySQLコンテナ
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "golang_login_test"
    volumes:
      - ./mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
